development:
  adapter: postgresql
  encoding: unicode
  database: chitter
  pool: 2
  username: Ajay Mungur
  password: tlN2rM332J

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_URI'] %>
  database: <%= ENV['DATABASE_URI'] %>
  username: <%= ENV['DATABASE_URI'] %>
  password: <%= ENV['DATABASE_URI'] %>
