development:
  adapter: postgresql
  encoding: unicode
  database: chitter
  pool: 2
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  pool: 2
  host: <%= ENV['DATABASE_URI'] %>
  database: <%= ENV['DATABASE_URI'] %>
  username: <%= ENV['DATABASE_URI'] %>
  password: <%= ENV['DATABASE_URI'] %>
